// <auto-generated />
using MahjongBuddy.EntityFramework.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MahjongBuddy.EntityFramework.Migrations
{
    [DbContext(typeof(MahjongBuddyDbContext))]
    [Migration("20200318162108_UpdateSeed")]
    partial class UpdateSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("MahjongBuddy.Core.Tile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tile 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tile 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
